# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "18:30"
    groups:
      python-packages:
        patterns:
          - "*"
    versioning-strategy: widen
    ignore:
      - dependency-name: "tornado"
      # The tornado issue partially recorded in the Kanbanize ticket:
      # https://instana.kanbanize.com/ctrl_board/197/cards/135147/details/, and there is an AHA Idea about it.
      - dependency-name: "google-cloud-pubsub"
      # google-cloud-pubsub (Collecting google-cloud-pubsub<=2.1.0 (from -r tests/requirements-310.txt (line 11)))
      - dependency-name: "sanic"
      # The lagging of the Sanic version is a known issue for at least a year, the oldest ticket is on the archived board:
      # https://instana.kanbanize.com/ctrl_board/49/cards/102939/details/
      # which is referenced from a ticket on our current board:
      # https://instana.kanbanize.com/ctrl_board/197/cards/109698/details/
      - dependency-name: "urllib3"
      # urllib3 (Collecting urllib3<1.27,>=1.26.5 (from instana==2.0.5->-r requirements.txt (line 2)))
      - dependency-name: "starlette"
      # starlette (Collecting starlette<0.28.0,>=0.27.0 (from fastapi>=0.92.0->-r tests/requirements-310.txt (line 7))
      #- dependency-name: "couchbase"
      - dependency-name: "protobuf"
      - dependency-name: "importlib-metadata"
      # fails for python-3.7